name: GitHub Actions Maven Build Example

on:
  push:
    branches: [master]

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v2

      - name: Step 2 - Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          discribtion: 'zulu'

      - name: Step 3 - Build Maven Project
        run: mvn --batch-mode -DskipTests package

      - name: Step 4 - Run test cases 
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
